// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	  int N = Integer.parseInt(args[0]);
	  int small = 0;
	  int big = 0;
	  for (int i = 1; i <= N; i++){
		if(Math.random() <0.5){
			small ++;
		}else{
		big++;
		}
		}
		if (big == 0) {
			System.out.println("> 0.5: " + small +" times");
			System.out.println("<= 0.5: " + big + " times");
		}
		else{
			System.out.println("> 0.5: " + big +" times");
			System.out.println("<= 0.5: " + small + " times");
			double ratio = ((double)small /(double)big);
			System.out.println("Ratio: " +  ratio );
		}
		
	
		
	  }
	  

	}

